# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# /tmp/kitware-geospatial-recipes_docker/recipes/segmentation, last modified Mon Aug  6 14:24:32 2018
# ------------------------------------------------

package:
    name: core3d-purdue
    version: 0.1
source:
    git_tag: packaging-required-fixes
    git_url: git@gitlab.kitware.com:core3d/core3d-purdue.git

requirements:
  build:
  - toolchain
  - cmake
  - ninja
  - eigen
  - liblas
  - cgal
  - pcl
  - vtk=v8.1.1
  - flann
  
  run:
  - eigen
  - cgal
  - flann
  - liblas
  - pcl
  - vtk=v8.1.1


    
about:
    home: https://gitlab.kitware.com/core3d/core3d-purdue/
    summary: Files are shared by the core3d Purdue team.
extra:
    copy_test_source_files: true
    final: true
