# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# /tmp/kitware-geospatial-recipes_docker/recipes/purdue-reconstruction, last modified Thu Aug 16 17:01:49 2018
# ------------------------------------------------

package:
    name: purdue-reconstruction
    version: 0.1.1
source:
    patches:
        - purdue-reconstruction.patch
    sha256: b66a548ca83bb326349993cd36a57be74808092d139fa527c7433f69ffe88de7
    url: core3d-purdue-0.1.0-3.tar.gz
build:
    string: '0'
requirements:
    build:
      - toolchain
      - cmake
      - ninja
      - pcl
      - vtk=v8.1.1
      - cgal

    run:
      - pcl
      - vtk=v8.1.1
      - cgal

about:
    home: https://gitlab.kitware.com/core3d/core3d-purdue/
    summary: Files are shared by the core3d Purdue team.
extra:
    copy_test_source_files: true
    final: true
