{% set version = "0.1.0" %}

package:
  name: pubgeo-core3d-metrics
  version: {{ version }}

source:
  git_rev: d805cc838596a24df64178db019b21f7cf61d1da
  git_url: https://github.com/pubgeo/core3d-metrics.git

build:
  number: 5
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - gdal
    - laspy
    - matplotlib
    - numpy
    - scipy
    - jsonschema
    - pubgeo-tools

test:
  imports:
    - core3dmetrics

about:
  home: https://github.com/pubgeo/core3d-metrics
  license: MIT
  summary: Performs metric analysis for 3D models
