package:
  name: texture-atlas
  version: {{ environ['GIT_DESCRIBE_TAG'] ~ "." ~ environ['GIT_DESCRIBE_NUMBER'] ~ "." ~ environ['GIT_DESCRIBE_HASH'] }}

source:
#  git_rev: {{ sha }}
  git_branch: master
  git_url: git@gitlab.kitware.com:core3d/core3d-keu.git
  patches:
    - gdal-headers.patch

requirements:
  build:
    - cmake
    - ninja
    - vtk
    - eigen 3.3.3.*
    - opencv 3.3.1.*
    - libgdal 2.2.3.*
  run:
    - vtk
    - eigen 3.3.3.*
    - opencv 3.3.1.*
    - libgdal 2.2.3.*

test:
  commands:
    - run_texture_mapping
    - run_only_atlases_fusion
    - run_only_obj_generation
