package:
  name: texture-atlas
  version: {{ environ['GIT_DESCRIBE_TAG'] ~ "." ~ environ['GIT_DESCRIBE_NUMBER'] ~ "." ~ environ['GIT_DESCRIBE_HASH'] }}

source:
  git_tag: v1.0.1
  git_url: git@gitlab.kitware.com:core3d/core3d-keu.git

requirements:
  build:
    - cmake
    - ninja
    - vtk v8.1.1.*    # vtk from kitware-geospatial
    - eigen 3.3.3.*
    - opencv 3.3.1.*
    - libgdal 2.2.*
    # otherwise we get an undefined error
    - x264 20131218
    - libboost 1.67.*
  run:
    - vtk v8.1.1.*    # vtk from kitware-geospatial
    - eigen 3.3.3.*
    - opencv 3.3.1.*
    - libgdal 2.2.*
    # otherwise we get an undefined error
    - x264 20131218
    - libboost 1.67.*
    - kealib 1.4.7.*

test:
  commands:
    - run_texture_mapping
