{% set version = "0.1.0" %}

package:
  name: pubgeo-tools
  version: {{ version }}

source:
  git_rev: 5223661082f13073f4e0ba0245d777f7292b65c8
  git_url: https://github.com/pubgeo/pubgeo.git

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - cmake
    - ninja
    - libgdal
    - libpdal
  run:
    - libgdal
    - libpdal

about:
  home: http://www.jhuapl.edu/pubgeo.html
  license: MIT
  summary: Geospatial tools for 3D registration and scene classification
